[package]
name = "hxlauncher"
version = "0.1.0"
description = "Minecraft launcher"
license = "MIT"
edition = "2021"
[lib]
name = "hxlauncher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
[build-dependencies]
dotenvy = "0.15"
tauri-build = { version = "2", features = [] }
[dependencies]
mc-launcher-core = "=0.1.2"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
tokio = { version = "1", features = ["full"] }
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service"] }
sha1 = "0.10"
zip = { version = "2", default-features = false, features = ["deflate"] }
futures-util = "0.3"
regex = "1"
sysinfo = "0.35"
minecraft-msa-auth = "0.5"
async-trait = "0.1"
oauth2 = "5"
auth-http = { package = "reqwest", version = "0.13", default-features = false, features = ["rustls"] }
tokio-util = "0.7"
rustls = { version = "0.23", features = ["aws_lc_rs"] }

base64 = "0.22"

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { version = "0.3", default-features = false, features = ["NSWindow", "NSButton", "NSControl", "NSView", "NSResponder"] }
